/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import documentation from "@strapi/plugin-documentation/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import strapiGoogleAuth from "strapi-google-auth/strapi-admin";
import cookieManager from "strapi-plugin-cookie-manager/strapi-admin";
import customApi from "strapi-plugin-custom-api/strapi-admin";
import importExportEntries from "strapi-plugin-import-export-entries/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "strapi-cloud": strapiCloud,
    documentation: documentation,
    i18n: i18N,
    "users-permissions": usersPermissions,
    "strapi-google-auth": strapiGoogleAuth,
    "cookie-manager": cookieManager,
    "custom-api": customApi,
    "import-export-entries": importExportEntries,
  },
});
